#!/bin/sh

PID_FILE=/var/run/librarian.pid

start() {
  [ ! -f $PID_FILE ] || exit 0
  echo -n "Starting librarian: "
  /usr/bin/python -m librarian.app > /dev/null 2>&1 &
  if [ $? ]; then
    echo $! > $PID_FILE
    echo "OK"
  else
    echo "FAILED"
  fi
}

stop() {
  if [ -f $PID_FILE ] ; then
    echo -n "Stopping librarian: "
    kill $(cat $PID_FILE)
    rm $PID_FILE
    echo "OK"
  fi
}

restart() {
  stop
  /bin/sleep 1
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?
