#!/bin/sh

PID_FILE=/var/run/wptdm.pid

start() {
  echo -n "Starting wptdm: "
  start-stop-daemon -S -q -p $PID_FILE --exec /usr/sbin/wptdm -- -d -r --pid-file $PID_FILE
  if [ $? ]; then
    echo "OK"
  else
    echo "FAILED"
  fi
}

stop() {
  echo -n "Stopping wptdm: "
  start-stop-daemon -K -q -p $PID_FILE
  [ -f $PID_FILE ] && rm $PID_FILE
  echo "OK"
}

restart() {
  stop
  /bin/sleep 1
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?
